name: GitHub Activity

on:
  schedule:
    - cron: '*/120 * * * *' # https://crontab.guru/#*/120_*_*_*_*
  workflow_dispatch:

jobs:
  build:
    name: Update the README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
